2021-07-30 19:35:30,395 INFO    MainThread:6576 [wandb_setup.py:_flush():69] setting env: {}
2021-07-30 19:35:30,395 INFO    MainThread:6576 [wandb_setup.py:_flush():69] setting login settings: {}
2021-07-30 19:35:30,395 INFO    MainThread:6576 [wandb_init.py:_log_setup():338] Logging user logs to D:\Roee_Yevgeniy\DeepAdv3D\wandb\run-20210730_193530-3pk46odk\logs\debug.log
2021-07-30 19:35:30,395 INFO    MainThread:6576 [wandb_init.py:_log_setup():339] Logging internal logs to D:\Roee_Yevgeniy\DeepAdv3D\wandb\run-20210730_193530-3pk46odk\logs\debug-internal.log
2021-07-30 19:35:30,395 INFO    MainThread:6576 [wandb_init.py:init():371] calling init triggers
2021-07-30 19:35:30,395 INFO    MainThread:6576 [wandb_init.py:init():378] wandb.init called with sweep_config: {}
config: {}
2021-07-30 19:35:30,395 INFO    MainThread:6576 [wandb_init.py:init():420] starting backend
2021-07-30 19:35:30,395 INFO    MainThread:6576 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=spawn, using: spawn
2021-07-30 19:35:30,395 INFO    MainThread:6576 [backend.py:ensure_launched():135] starting backend process...
2021-07-30 19:35:30,795 INFO    MainThread:6576 [backend.py:ensure_launched():140] started backend process with pid: 17608
2021-07-30 19:35:30,795 INFO    MainThread:6576 [wandb_init.py:init():425] backend started and connected
2021-07-30 19:35:30,795 INFO    MainThread:6576 [wandb_init.py:init():473] updated telemetry
2021-07-30 19:35:30,795 INFO    MainThread:6576 [wandb_init.py:init():492] communicating current version
2021-07-30 19:35:35,795 INFO    MainThread:6576 [wandb_init.py:init():505] communicating run to backend with 30 second timeout
2021-07-30 19:35:35,803 ERROR   MainThread:6576 [wandb_init.py:init():788] error
Traceback (most recent call last):
  File "C:\Users\ido.igip1\Anaconda3\envs\DeepAdv3D\lib\site-packages\wandb\sdk\wandb_init.py", line 762, in init
    run = wi.init()
  File "C:\Users\ido.igip1\Anaconda3\envs\DeepAdv3D\lib\site-packages\wandb\sdk\wandb_init.py", line 506, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "C:\Users\ido.igip1\Anaconda3\envs\DeepAdv3D\lib\site-packages\wandb\sdk\interface\interface.py", line 666, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "C:\Users\ido.igip1\Anaconda3\envs\DeepAdv3D\lib\site-packages\wandb\sdk\interface\interface.py", line 654, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "C:\Users\ido.igip1\Anaconda3\envs\DeepAdv3D\lib\site-packages\wandb\sdk\interface\interface.py", line 544, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\ido.igip1\Anaconda3\envs\DeepAdv3D\lib\site-packages\wandb\sdk\interface\interface.py", line 549, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
